//Setoutputs
ldi R16, 0xFF
out DDRB, R16
out DDRD, R16
;out PortD, R17


/*
H-Sync --- PortD N:2
	Back Portch		:1.92us		High
	Pulse			:3.84us		Low
	Front Portch	:0.64us		High
	Display Time	:25.6us		High

V-Sync --- PortD N:1
	Back Portch		:928us		High
	Pulse			:64us		Low
	Front Portch	:320us		High
	Display Time	:15360us	High
*/


//lets try, 640x480
//that's 640 vertical lines and 480 Horizontal lines
//so, 1023 H-Sync pulses, then a V-Sync

//use R16 and R17 for Hsync usual and pulse
//use R16 and R18 for Vsync usual and pulse
//use R19 for colour
ldi R16, 0x03 // usual
ldi R17, 0x01 //HSync pulse
ldi R18, 0x00 //VSynce pluse
ldi R19, 0x23 //colour on

out PortD, R16




//begin
call GraphicLoop2
GraphicLoop:
	/*call H_Loop

	cpi R19, 0xE0		//takes 0.05
	brne GraphicLoop	//takes 0.1 to loop back, and 0.05 to continue on
		nop
	cpi R20, 0x01		//takes 0.05
	brne GraphicLoop	//takes 0.1 to loop back, and 0.05 to continue on
		nop
*/
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3

	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3
	call H_Loop3	
	call H_Loop3	

	call H_Loop3	
	call H_Loop3	
	call H_Loop3	
		   
	call V_Loop3
jmp GraphicLoop
	

#include "Includes/HandVloops.asm"
#include "Includes/HandVloops_2.asm"
#include "Includes/HandVloops_3.asm"
#include "Includes/HandVloops_4.asm"
#include "Includes/HandVloops_5.asm"
#include "Includes/GraphicLoop2.asm"
#include "Includes/Wait_16mhz.asm"
